language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - android-33

before_install:
  - chmod +x gradlew

script:
  - ./gradlew clean build

notifications:
  email: israttasnimesha1046@gmail.com